[package]
name = "qc_rust_use"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
crate_lib= { path = "./crate_lib" }
tokio = "1.44.2"
reqwest = { version = "0.12.15", features = ["json"] }
serde_json = "1.0.140"



[[bin]]
name = "qc_rust_use"
path = "src/main.rs"
